name: Upstream Sync

on:
  schedule:
    - cron: "0 0 * * *" # 每天0点自动同步
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: Aethersailor/Custom_OpenClash_Rules
          upstream_sync_branch: main
          target_sync_branch: main
          test_mode: false
